[tools]
usage = "latest"
bat = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
ghq = "latest"
gh = "latest"
jq = "latest"
deno = "2.4.3"
go = "1.24.5"
node = "22.18.0"
python = "3.13.5"
rust = "1.88.0"
