[tools]
# tools
bat = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gemini = "latest"
gh = "latest"
ghq = "latest"
jq = "latest"
usage = "latest"

# languages
deno = "2.4"
go = "1.25"
node = "22"
python = "3.13"
rust = "1.89"
