[settings]
lockfile = true
lockfile_platforms = ["linux-x64", "macos-arm64"]

[tools]
# tools
antigravity-cli = "latest"
bat = "latest"
codex = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
jq = "latest"
neovim = "latest"
usage = "latest"

# languages
deno = "2.9"
go = "1.26"
node = "24"
python = "3.14"
rust = "1.97"
