[tools]
# tools
usage = "latest"
bat = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
jq = "latest"

# languages
deno = "2.4"
go = "1.24"
node = "lts"
python = "3.13"
rust = "1.88"
